"""Database creation

Revision ID: 2b8781369db8
Revises: 
Create Date: 2023-03-08 16:52:50.589877

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2b8781369db8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.VARCHAR(), nullable=True),
                    sa.Column('last_name', sa.VARCHAR(), nullable=True),
                    sa.Column('username', sa.VARCHAR(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('news',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('topic', sa.VARCHAR(), nullable=True),
                    sa.Column('main_text', sa.VARCHAR(), nullable=False),
                    sa.Column('image_url', sa.VARCHAR(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_table('users')
    # ### end Alembic commands ###
